name: default
on:
  push:
  pull_request:
    types:
      - opened

jobs:
  linter:
    runs-on: [ubuntu-24.04]
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Prettier
        run: pnpm exec prettier --check src/**/*.ts
      - name: Typescript types check
        run: pnpm exec tsc --noEmit
  test:
    runs-on: [ubuntu-24.04]
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Vitest
        run: pnpm run test
      - name: Typescript types check
        run: pnpm exec tsc --noEmit
