name: default
on:
  pull_request:
    types:
      - reopened
      - opened

env:
  ENV: '$HOME/.bashrc'

jobs:
  setup:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Installs node
        run: sudo apt install nodejs
      - name: Installs pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -
      - name: reload source
        run: source /home/runner/.bashrc
